# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'tsog' do
  pod 'PDKeychainBindingsController'
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Invites'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  
  pod 'FirebaseUI/Auth', '~> 1.0'
  pod 'FirebaseUI/Google', '~> 1.0'
  pod 'FirebaseUI/Facebook', '~> 1.0'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end

