# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'tsog' do
  pod 'PDKeychainBindingsController'
  pod 'Analytics', '~> 2.0.17'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Amplitude-iOS', :git => 'git@github.com:thuydx55/Amplitude-iOS.git', :branch => 'fix_sqlite_importing_3.2.0'
end

target 'tsog-desktop' do

end

