# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'tsog' do
  pod 'PDKeychainBindingsController'
  pod 'Analytics'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'EZAudio', :git => 'git@github.com:thuydx55/EZAudio.git'
end

target 'tsog-desktop' do

end

