/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Decoder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Decoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_Decoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Decoder() {
    this(PocketSphinxJNI.new_Decoder__SWIG_0(), true);
  }

  public Decoder(Config config) {
    this(PocketSphinxJNI.new_Decoder__SWIG_1(Config.getCPtr(config), config), true);
  }

  public void reinit(Config config) {
    PocketSphinxJNI.Decoder_reinit(swigCPtr, this, Config.getCPtr(config), config);
  }

  public void loadDict(String fdict, String ffilter, String format) {
    PocketSphinxJNI.Decoder_loadDict(swigCPtr, this, fdict, ffilter, format);
  }

  public void saveDict(String dictfile, String format) {
    PocketSphinxJNI.Decoder_saveDict(swigCPtr, this, dictfile, format);
  }

  public void addWord(String word, String phones, int update) {
    PocketSphinxJNI.Decoder_addWord(swigCPtr, this, word, phones, update);
  }

  public String lookupWord(String word) {
    return PocketSphinxJNI.Decoder_lookupWord(swigCPtr, this, word);
  }

  public Lattice getLattice() {
    long cPtr = PocketSphinxJNI.Decoder_getLattice(swigCPtr, this);
    return (cPtr == 0) ? null : new Lattice(cPtr, false);
  }

  public Config getConfig() {
    long cPtr = PocketSphinxJNI.Decoder_getConfig(swigCPtr, this);
    return (cPtr == 0) ? null : new Config(cPtr, true);
  }

  public static Config defaultConfig() {
    long cPtr = PocketSphinxJNI.Decoder_defaultConfig();
    return (cPtr == 0) ? null : new Config(cPtr, true);
  }

  public static Config fileConfig(String path) {
    long cPtr = PocketSphinxJNI.Decoder_fileConfig(path);
    return (cPtr == 0) ? null : new Config(cPtr, true);
  }

  public void startStream() {
    PocketSphinxJNI.Decoder_startStream(swigCPtr, this);
  }

  public void startUtt() {
    PocketSphinxJNI.Decoder_startUtt(swigCPtr, this);
  }

  public void endUtt() {
    PocketSphinxJNI.Decoder_endUtt(swigCPtr, this);
  }

  public int processRaw(short[] SDATA, long NSAMP, boolean no_search, boolean full_utt) {
    return PocketSphinxJNI.Decoder_processRaw(swigCPtr, this, SDATA, NSAMP, no_search, full_utt);
  }

  public void setRawdataSize(long size) {
    PocketSphinxJNI.Decoder_setRawdataSize(swigCPtr, this, size);
  }

  public short[] getRawdata() {
  return PocketSphinxJNI.Decoder_getRawdata(swigCPtr, this);
}

  public Hypothesis hyp() {
    long cPtr = PocketSphinxJNI.Decoder_hyp(swigCPtr, this);
    return (cPtr == 0) ? null : new Hypothesis(cPtr, true);
  }

  public FrontEnd getFe() {
    long cPtr = PocketSphinxJNI.Decoder_getFe(swigCPtr, this);
    return (cPtr == 0) ? null : new FrontEnd(cPtr, false);
  }

  public Feature getFeat() {
    long cPtr = PocketSphinxJNI.Decoder_getFeat(swigCPtr, this);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public boolean getInSpeech() {
    return PocketSphinxJNI.Decoder_getInSpeech(swigCPtr, this);
  }

  public FsgModel getFsg(String name) {
    long cPtr = PocketSphinxJNI.Decoder_getFsg(swigCPtr, this, name);
    return (cPtr == 0) ? null : new FsgModel(cPtr, false);
  }

  public void setFsg(String name, FsgModel fsg) {
    PocketSphinxJNI.Decoder_setFsg(swigCPtr, this, name, FsgModel.getCPtr(fsg), fsg);
  }

  public void setJsgfFile(String name, String path) {
    PocketSphinxJNI.Decoder_setJsgfFile(swigCPtr, this, name, path);
  }

  public void setJsgfString(String name, String jsgf_string) {
    PocketSphinxJNI.Decoder_setJsgfString(swigCPtr, this, name, jsgf_string);
  }

  public String getKws(String name) {
    return PocketSphinxJNI.Decoder_getKws(swigCPtr, this, name);
  }

  public void setKws(String name, String keyfile) {
    PocketSphinxJNI.Decoder_setKws(swigCPtr, this, name, keyfile);
  }

  public void setKeyphrase(String name, String keyphrase) {
    PocketSphinxJNI.Decoder_setKeyphrase(swigCPtr, this, name, keyphrase);
  }

  public void setAllphoneFile(String name, String lmfile) {
    PocketSphinxJNI.Decoder_setAllphoneFile(swigCPtr, this, name, lmfile);
  }

  public NGramModel getLm(String name) {
    long cPtr = PocketSphinxJNI.Decoder_getLm(swigCPtr, this, name);
    return (cPtr == 0) ? null : new NGramModel(cPtr, true);
  }

  public void setLm(String name, NGramModel lm) {
    PocketSphinxJNI.Decoder_setLm(swigCPtr, this, name, NGramModel.getCPtr(lm), lm);
  }

  public void setLmFile(String name, String path) {
    PocketSphinxJNI.Decoder_setLmFile(swigCPtr, this, name, path);
  }

  public LogMath getLogmath() {
    long cPtr = PocketSphinxJNI.Decoder_getLogmath(swigCPtr, this);
    return (cPtr == 0) ? null : new LogMath(cPtr, true);
  }

  public void setSearch(String search_name) {
    PocketSphinxJNI.Decoder_setSearch(swigCPtr, this, search_name);
  }

  public String getSearch() {
    return PocketSphinxJNI.Decoder_getSearch(swigCPtr, this);
  }

  public int nFrames() {
    return PocketSphinxJNI.Decoder_nFrames(swigCPtr, this);
  }

  public SegmentList seg() {
    long cPtr = PocketSphinxJNI.Decoder_seg(swigCPtr, this);
    return (cPtr == 0) ? null : new SegmentList(cPtr, false);
  }

  public NBestList nbest() {
    long cPtr = PocketSphinxJNI.Decoder_nbest(swigCPtr, this);
    return (cPtr == 0) ? null : new NBestList(cPtr, false);
  }

}
