/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class SegmentList implements Iterable<Segment> {

  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SegmentList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SegmentList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @Override
  public java.util.Iterator<Segment> iterator () {
    return iter();
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_SegmentList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SegmentList(SWIGTYPE_p_ps_decoder_t ptr) {
    this(PocketSphinxJNI.new_SegmentList(SWIGTYPE_p_ps_decoder_t.getCPtr(ptr)), true);
  }

  private SegmentIterator iter() {
    long cPtr = PocketSphinxJNI.SegmentList_iter(swigCPtr, this);
    return (cPtr == 0) ? null : new SegmentIterator(cPtr, true);
  }

}
