var res = {
    Account_plist: "account.plist",
    Account_png: "account.png",
    School_plist: "school.plist",
    School_png: "school.png",
    Loading_plist: "loading.plist",
    Loading_png: "loading.png",
    Abc_plist: "abc.plist",
    Abc_png: "abc.png",

    // Temporary
    LoginSucceed_png: "login-succeed.png",
    Welcome_jpg:"welcome.jpg",
    // Bg
    Bg_account_jpg: "bg/bg-account.jpg",
    Bg_school_jpg: "bg/bg-school.jpg",
    Bg_game_jpg: "bg/bg-game.jpg",
    // Font
    RedFont_png: "red-font-export.png",
    YellowFont_png: "yellow-font-export.png",
    PurpleFont_png: "purple-font-export.png",
    GreenFont_png: "green-font-export.png",
    RedFont_fnt: "red-font-export.fnt",
    YellowFont_fnt: "yellow-font-export.fnt",
    PurpleFont_fnt: "purple-font-export.fnt",
    GreenFont_fnt: "green-font-export.fnt",
    // Sound
    bubble_sound_mp3: "res/sound/bubble.mp3",
    rustle_sound_mp3: "res/sound/rustle.mp3",
    bubble_scroll_sound_mp3: "res/sound/bubble-scroll.mp3",
    welcome_sound_mp3: "res/sound/welcome.mp3",
    change_scene_mp3: "res/sound/change-scene.mp3",
    right_password_mp3: "res/sound/right-password.mp3",
    wrong_password_mp3: "res/sound/wrong-pass.mp3",
    background_mp3: "res/sound/background.mp3",

    Forest_Config_JSON: "config/forest.json",
    Game_Config_JSON: "config/game.json",
    Room_Config_JSON: "config/room.json",
    Writing_config_JSON: "config/writing_test.json",
    Updated_config_JSON: "config/updated.json",
    Game_Object_JSON: "config/game_object.json",

    forest_jpg : "res/forest.jpg",
    room_jpg: "Bedroom-screen.jpg",
    room_roof_png: "bedroom-roof.png",
    room_clock_png: "bedroom-clock.png",
    room_ribbon_png: "bedroom-ribbon.png",
    room_window_png: "bedroom-window.png",
 
    GrayButton_png: "res/gray-button.png",
    Red_PlaceHolder_jpg: "res/red-place-holder.jpg",
    Button_Refresh_png: "res/refresh-button.png",
    BG_jpg: "BG.jpg",
 
    // plist file
    Forest_plist: "forest.plist",
    Forest_png: "forest.png",
    NewAccount_Plist: "newaccount.plist",
    NewAccount_Png: "newaccount.png",
    Figure_Game_Plist: "figure-game.plist",
    Figure_Game_Png: "figure-game.png",
 
    // Animals
    Ant_png: "animals/ant.png",
    Fish_png: "animals/fish.png",
    Bear_png: "animals/bear.png",
    Bee_png: "animals/bee.png",
    Bird_png: "animals/bird.png",
    Cat_png: "animals/cat.png",
    Cow_png: "animals/cow.png",
    Duck_png: "animals/duck.png",
    Elephant_png: "animals/elephant.png",
    Horse_png: "animals/horse.png",
    Insect_png: "animals/insect.png",
    Lion_png: "animals/lion.png",
    Monkey_png: "animals/monkey.png",
    Frog_png: "animals/frog.png",
    Owl_ong:"animals/owl.png",
    Tiger_png: "animals/tiger.png",
    Rat_png: "animals/rat.png",
    Panda_png: "animals/panda.mp3",
    Nest_png: "animals/nest.png",
    Puppy_png: "animals/puppy.png",
    Rabbit_png: "animals/rabbit.png",
    Pig_png: "animals/pig.png",
    Sheep_png: "animals/sheep.png",
    Snail_png: "animals/snail.png",
    Octopus_png: "animals/octopus.png",
    Dolphin_png: "animals/dolphin.png",
    Crocodile_png: "animals/crocodile.png",
    Zebra_png: "animals/zebra.png",
    Goldfish_png: "animals/goldfish.png",
    Eagle_png: "animals/eagle.png",
    Hamster_png: "animals/hamster.png",
    Goat_png: "animals/goat.png",
    Giraffe_png: "animals/giraffe.png",
    Deer_png: "animals/deer.png",
    Kitten_png: "animals/kitten.png",
    Snake_png: "animals/snake.png",
    Turtle_png : "animals/turtle.png",
    Fly_png: "animals/fly.png",
    Squirrel_png: "animals/squirrel.png",
    Fox_png: "animals/fox.png",
    Shark_png: "animals/shark.png",
    Camel_png: "animals/camel.png",
    New_theme_joselito_png:"new_therme_joselito.png",
    // Cheetah_png: "animals/cheetah.png",
    // Chicken_png: "animals/chicken.png",
    // Kangaroo_png: "animals/kangaroo.png",
    // Lobster_png: "animals/lobster.png",
    // Scorpion_png:"animals/scorpion.png",
    // Seal_png: "animals/seal.png",
    // Wolf_png: "animals/wolf.png",
    
 
    // Things
    Map_png: "things/map.png",
    Grap_png: "things/grape.png",
    Watch_png: "things/watch.png",
    Desk_png: "things/desk.png",
    Duster_png: "things/duster.png",
    Jar_jpg: "things/jar.png",
    Hat_jpg: "things/hat.png",
    Lamp_jpg: "things/lamp.png",
    Apple_png: "things/apple.png",
    Banana_png: "things/banana.png",
    Book_png: "things/book.png",
    Chair_png: "things/chair.png",
    Pencils_png: "things/pencils.png",
    Egg_png: "things/egg.png",
    Potato_png: "things/potato.png",
    Towel_png: "things/towel.png",
    Umbrella_png: "things/umbrella.png",
    Key_png:"things/key.png",
    Sock_png: "things/sock.png",
    Joker_png: "things/joker.png",
    Kite_png: "things/kite.png",
    Strawberry_png: "things/strawberry.png",
    Pen_png: "things/pen.png",
    Table_png: "things/table.png",
    Abacus_png: "things/abacus.png",
    Flag_png: "things/flag.png",
    Onion_png: "things/onion.png",
    Medicine_png: "things/medicine.png",
    Feather_png: "things/feather.png",
    Tomato_png: "things/tomato.png",
    Computer_png: "things/computer.png",
    Eraser_png: "things/eraser.png",
    Gift_png: "things/gift.png",
    Insect_png: "things/insect.png",
    Juice_png: "things/juice.png",
    Lemon_png: "things/lemon.png",
    Nail_png: "things/nail.png",
    Queen_png: "things/queen.png",
    Raspberry_png: "things/raspberry.png",
    Toytrain_png: "things/toytrain.png",
    Uniform_png: "things/uniform.png",
    Vegetable_png: "things/vegetable.png",
    Vehicle_png: "things/vehicle.png",
    Waterlemon_png: "things/waterlemon.png",
    Xylyphone_png: "things/xylyphone.png",
    Orange_png: "things/orange.png",
    Nest_png: "things/nest.png",
 
    // Hud
 
    Hud_plist: "hud/hud.plist",
    Hud_png: "hud/hud.png",
    Hud_progress_bar_png: "hud/progress-bar.jpg",
    Hud_progress_bar_alpha_png: "hud/progress-bar-alpha.jpg",
    HudFont_fnt: "hud-font.fnt",
    HudFont_png: "hud-font.png",
    CloudEmpty_png: "temp/cloud-empty.png",
    BtnNormal_png: "temp/btn-normal.png",
    BtnPressed_png: "temp/btn-pressed.png",
 
    // Shader
    SpriteDistort_fsh: "res/shader/SpriteDistort.fsh",
    SolidColor_fsh: "res/shader/SolidColor.fsh",
    ScrollingTexture_fsh: "res/shader/ScrollingTexture.fsh",
    PositionTextureColor_vsh: "res/shader/PositionTextureColor.vsh",
    PositionTextureColor_noMVP_vsh: "res/shader/PositionTextureColor_noMVP.vsh",
 
    // Effect
    Smoke_effect_plist: "effect-smoke.plist",
    Smoke_effect_png: "effect-smoke.png",
    Sparkle_effect_png: "sparkle-effect.png",
    Sparkle_effect_plist: "sparkle-effect.plist",
    Tutorial_png: "tutorial.png",
    Tutorial_plist: "tutorial.plist",
 
    // Smoke_sound: "res/smoke-sound.mp3"
 
    // Sound effect
    DROP_mp3: "sounds/drop.mp3",
    PICKUP_mp3: "sounds/pickup.mp3",
    SMOKE_mp3: "sounds/smoke.mp3",
    BEGIN_BEDROOM_mp3: "sounds/beginroom-sound_english.mp3",
    BEGIN_FOREST_mp3: "sounds/beginforest-sound_english.mp3",
    SPEAK_AFTER_mp3: "sounds/speak-after_english.mp3",
    BEGIN_SPEAKING_ADI_mp3: "sounds/begin-talkingAdi_english.mp3",

    // speaking effect
    Succeed_sfx: "res/sounds/speaking-success.mp3",
    Failed_sfx: "res/sounds/speaking-failure.mp3",
 
    //countdown
    COUNTDOWN_mp3 : "res/sounds/Countdown.mp3",
    
    // BG sound 
    BACKGROUND_mp3: "sounds/background.mp3",
 
    Adidog_json: "Adidog/ConCho.json",
    Adidog_atlas: "AdiDog/ConCho.atlas",
    Adidog_png2: "AdiDog/ConCho.png",
 
    Plus_png: "plus.png",
    Create_png: "create-button.png",

    // TMX
    ABC_TMX: "res/abc.tmx",
    Figure_TMX: "res/figure-game.tmx",

    HELVETICARDBLK_ttf: {type:"font", name:"HELVETICARDBLK", srcs:["res/font/HELVETICARDBLK.TTF"]},
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}