var res = {
    Account_plist: "account.plist",
    Account_png: "account.png",
    School_plist: "school.plist",
    School_png: "school.png",
    Game_plist: "game.plist",
    Game_png: "game.png",
    Loading_plist: "loading.plist",
    Loading_png: "loading.png",
    // Temporary
    LoginSucceed_png: "login-succeed.png",
    Welcome_jpg:"welcome.jpg",
    // Bg
    Bg_account_jpg: "bg/bg-account.jpg",
    Bg_school_jpg: "bg/bg-school.jpg",
    Bg_game_jpg: "bg/bg-game.jpg",
    // Font
    RedFont_png: "red-font-export.png",
    YellowFont_png: "yellow-font-export.png",
    PurpleFont_png: "purple-font-export.png",
    GreenFont_png: "green-font-export.png",
    RedFont_fnt: "red-font-export.fnt",
    YellowFont_fnt: "yellow-font-export.fnt",
    PurpleFont_fnt: "purple-font-export.fnt",
    GreenFont_fnt: "green-font-export.fnt",
    // Sound
    bubble_sound_mp3: "res/sound/bubble.mp3",
    rustle_sound_mp3: "res/sound/rustle.mp3",
    bubble_scroll_sound_mp3: "res/sound/bubble-scroll.mp3",
    welcome_sound_mp3: "res/sound/welcome.mp3",
    change_scene_mp3: "res/sound/change-scene.mp3",
    right_password_mp3: "res/sound/right-password.mp3",
    wrong_password_mp3: "res/sound/wrong-pass.mp3",
    background_mp3: "res/sound/background.mp3",

    Forest_Config_JSON: "config/forest_config.json",
    Game_Config_JSON: "config/game_config.json",
    Room_Config_JSON: "config/room_config.json",

    forest_jpg : "res/forest.jpg",
    room_jpg: "Bedroom-screen.jpg",
    room_roof_png: "bedroom-roof.png",
    room_clock_png: "bedroom-clock.png",
    room_ribbon_png: "bedroom-ribbon.png",
    room_window_png: "bedroom-window.png",
 
    GrayButton_png: "res/gray-button.png",
    Red_PlaceHolder_jpg: "res/red-place-holder.jpg",
    Button_Refresh_png: "res/refresh-button.png",
    BG_jpg: "BG.jpg",
 
    // plist file
    Forest_plist: "forest.plist",
    Forest_png: "forest.png",
 
    // Animals
 
    Ant_png: "animals/ant.png",
    Fish_png: "animals/fish.png",
    Bear_png: "animals/bear.png",
    Bee_png: "animals/bee.png",
    Bird_png: "animals/bird.png",
    Cat_png: "animals/cat.png",
    Cow_png: "animals/cow.png",
    Duck_png: "animals/duck.png",
    Elephant_png: "animals/elephant.png",
    Horse_png: "animals/horse.png",
    Insect_png: "animals/insect.png",
    Lion_png: "animals/lion.png",
    Monkey_png: "animals/monkey.png",
    Frog_png: "animals/frog.png",
    Owl_ong:"animals/owl.png",
    Tiger_png: "animals/tiger.png",
    Rat_png: "animals/rat.png",
    Panda_png: "animals/panda.mp3",
    Nest_png: "animals/nest.png",
    Puppy_png: "animals/puppy.png",
    Rabbit_png: "animals/rabbit.png",
    Pig_png: "animals/pig.png",
    Sheep_png: "animals/sheep.png",
    Snail_png: "animals/snail.png",
    Octopus_png: "animals/octopus.png",
    Dolphin_png: "animals/dolphin.png",
    Crocodile_png: "animals/crocodile.png",
    Zebra_png: "animals/zebra.png",
    Goldfish_png: "animals/goldfish.png",
    Eagle_png: "animals/eagle.png",
    Hamster_png: "animals/hamster.png",
    Goat_png: "animals/goat.png",
    Giraffe_png: "animals/giraffe.png",
    Deer_png: "animals/deer.png",
    Kitten_png: "animals/kitten.png",
    Snake_png: "animals/snake.png",
    Turtle_png : "animals/turtle.png",
    Fly_png: "animals/fly.png",
    Squirrel_png: "animals/squirrel.png",
    Fox_png: "animals/fox.png",
    Shark_png: "animals/shark.png",
    Camel_png: "animals/camel.png",
    // Cheetah_png: "animals/cheetah.png",
    // Chicken_png: "animals/chicken.png",
    // Kangaroo_png: "animals/kangaroo.png",
    // Lobster_png: "animals/lobster.png",
    // Scorpion_png:"animals/scorpion.png",
    // Seal_png: "animals/seal.png",
    // Wolf_png: "animals/wolf.png",
 
 
    // Things
    Map_png: "things/map.png",
    Grap_png: "things/grape.png",
    Watch_png: "things/watch.png",
    Desk_png: "things/desk.png",
    Duster_png: "things/duster.png",
    Jar_jpg: "things/jar.png",
    Hat_jpg: "things/hat.png",
    Lamp_jpg: "things/lamp.png",
    Apple_png: "things/apple.png",
    Banana_png: "things/banana.png",
    Book_png: "things/book.png",
    Chair_png: "things/chair.png",
    Pencils_png: "things/pencils.png",
    Egg_png: "things/egg.png",
    Potato_png: "things/potato.png",
    Towel_png: "things/towel.png",
    Umbrella_png: "things/umbrella.png",
    Key_png:"things/key.png",
    Sock_png: "things/sock.png",
    Joker_png: "things/joker.png",
    Kite_png: "things/kite.png",
    Strawberry_png: "things/strawberry.png",
    Pen_png: "things/pen.png",
    Table_png: "things/table.png",
    Abacus_png: "things/abacus.png",
    Flag_png: "things/flag.png",
    Onion_png: "things/onion.png",
    Medicine_png: "things/medicine.png",
    Feather_png: "things/feather.png",
    Tomato_png: "things/tomato.png",
    Computer_png: "things/computer.png",
    Eraser_png: "things/eraser.png",
    Gift_png: "things/gift.png",
    Insect_png: "things/insect.png",
    Juice_png: "things/juice.png",
    Lemon_png: "things/lemon.png",
    Nail_png: "things/nail.png",
    Queen_png: "things/queen.png",
    Raspberry_png: "things/raspberry.png",
    Toytrain_png: "things/toytrain.png",
    Uniform_png: "things/uniform.png",
    Vegetable_png: "things/vegetable.png",
    Vehicle_png: "things/vehicle.png",
    Waterlemon_png: "things/waterlemon.png",
    Xylyphone_png: "things/xylyphone.png",
    Orange_png: "things/orange.png",
    Nest_png: "things/nest.png",
 
    // Hud
 
    Hud_plist: "hud/hud.plist",
    Hud_png: "hud/hud.png",
    Hud_progress_bar_png: "hud/progress-bar.jpg",
    Hud_progress_bar_alpha_png: "hud/progress-bar-alpha.jpg",
    HudFont_fnt: "hud-font-export.fnt",
    HudFont_png: "hud-font.png",
 
    // Shader
    SpriteDistort_fsh: "res/shader/SpriteDistort.fsh",
    SolidColor_fsh: "res/shader/SolidColor.fsh",
    ScrollingTexture_fsh: "res/shader/ScrollingTexture.fsh",
    PositionTextureColor_vsh: "res/shader/PositionTextureColor.vsh",
    PositionTextureColor_noMVP_vsh: "res/shader/PositionTextureColor_noMVP.vsh",
 
    // Effect
    Smoke_effect_plist: "effect-smoke.plist",
    Smoke_effect_png: "effect-smoke.png",
    Sparkle_effect_png: "sparkle-effect.png",
    Sparkle_effect_plist: "sparkle-effect.plist",
    Tutorial_png: "tutorial.png",
    Tutorial_plist: "tutorial.plist",
 
    // Smoke_sound: "res/smoke-sound.mp3"
 
    // Sound effect
    DROP_mp3: "sounds/drop.mp3",
    PICKUP_mp3: "sounds/pickup.mp3",
    SMOKE_mp3: "sounds/smoke.mp3",
 
 
    // Animal Sound
    ANT_mp3: "sounds/animals/ant.mp3",
    BEAR_mp3: "sounds/animals/bear.mp3",
    BEE_mp3: "sounds/animals/bee.mp3",
    BIRD_mp3: "sounds/animals/bird.mp3",
    CAT_mp3: "sounds/animals/cat.mp3",
    COW_mp3: "sounds/animals/cow.mp3",
    DOG_mp3: "sounds/animals/dog.mp3",
    DUCK_mp3: "sounds/animals/duck.mp3",
    ELEPHANT_mp3: "sounds/animals/elephant.mp3",
    FISH_mp3: "sounds/animals/fish.mp3",
    FROG_mp3: "sounds/animals/frog.mp3",
    HORSE_mp3: "sounds/animals/horse.mp3",
    INSECT_mp3: "sounds/animals/insect.mp3",
    LION_mp3: "sounds/animals/lion.mp3",
    MONKEY_mp3: "sounds/animals/monkey.mp3",
    NEST_mp3: "sounds/animals/nest.mp3",
    OWL_mp3: "sounds/animals/owl.mp3",
    PANDA_mp3: "sounds/animals/panda.mp3",
    RAT_mp3: "sounds/animals/rat.mp3",
    TIGER_mp3: "sounds/animals/tiger.mp3",
    ZEBRA_mp3: "sounds/animals/zebra.mp3",
    GOLDFISH_mp3: "sounds/animals/goldfish.mp3",
    EAGLE_mp3: "sounds/animals/eagle.mp3",
    HAMSTER_mp3: "sounds/animals/hamster.mp3",
    GOAT_mp3: "sounds/animals/goat.mp3",
    GIRAFFE_mp3: "sounds/animals/giraffe.mp3",
    DEER_mp3: "sounds/animals/deer.mp3",
    KITTEN_mp3: "sounds/animals/kitten.mp3",
    SNAKE_mp3: "sounds/animals/snake.mp3",
    TURTLE_mp3 : "sounds/animals/turtle.mp3",
    FLY_mp3: "sounds/animals/fly.mp3",
    SQUIRREL_mp3: "sounds/animals/squirrel.mp3",
    CAMEL_mp3: "sounds/animals/camel.mp3",
    CHEETAH_mp3:"sounds/animals/cheetah.mp3",
    CHICKEN_mp3: "sounds/animals/chicken.mp3",
    CHIMPANZEE_mp3: "sounds/animals/chimpanzee.mp3",
    CROCODILE_mp3: "sounds/animals/crocodile.mp3",
    DOLPHIN_mp3: "sounds/animals/dolphin.mp3",
    FOX_mp3: "sounds/animals/fox.mp3",
    GOAT_mp3: "sounds/animals/goat.mp3",
    GOLDFISH_mp3: "sounds/animals/goldfish.mp3",
    KANGAROO_mp3: "sounds/animals/kangaroo.mp3",
    PIG_mp3: "sounds/animals/pig.mp3",
    PUPPY_mp3: "sounds/animals/puppy.mp3",
    RABBIT_mp3:"sounds/animals/rabbit.mp3",
    SCORPION_mp3: "sounds/animals/scorpion.mp3",
    SEAL_mp3: "sounds/animals/seal.mp3",
    SHARK_mp3: "sounds/animals/shark.mp3",
    SHEEP_mp3: "sounds/animals/sheep.mp3",
    SNAIL_mp3: "sounds/animals/snail.mp3",
    SPIDER_mp3: "sounds/animals/spider.mp3",
    QUIRREL_mp3: "sounds/animals/quirrel.mp3",
    WOLF_mp3: "sounds/animals/wolf.mp3",
    LOBSTER_mp3: "sounds/animals/lobster.mp3",
    SNAKE_mp3: "sounds/animals/snake.mp3",
 
 
 
 
    // Things sound
    APPLE_1_mp3: "res/sounds/things/apple-1.mp3",
    APPLE_2_mp3: "res/sounds/things/apple-2.mp3",
    BANANA_1_mp3: "res/sounds/things/banana-1.mp3",
    BANANA_2_mp3: "res/sounds/things/banana-2.mp3",
    BOOK_1_mp3: "res/sounds/things/book-1.mp3",
    BOOK_2_mp3: "res/sounds/things/book-2.mp3",
    CHAIR_1_mp3: "res/sounds/things/chair-1.mp3",
    CHAIR_2_mp3: "res/sounds/things/chair-2.mp3",
    PENCILS_1_mp3: "res/sounds/things/pencils-1.mp3",
    PENCILS_2_mp3: "res/sounds/things/pencils-2.mp3",
    DESK_1_mp3: "res/sounds/things/desk-1.mp3",
    DESK_2_mp3: "res/sounds/things/desk-2.mp3",
    DUSTER_1_mp3: "res/sounds/things/duster-1.mp3",
    DUSTER_2_mp3: "res/sounds/things/duster-2.mp3",
    EGG_1_mp3: "res/sounds/things/egg-1.mp3",
    EGG_2_mp3: "res/sounds/things/egg-2.mp3",
    GRAPE_1_mp3: "res/sounds/things/grape-1.mp3",
    GRAPE_2_mp3: "res/sounds/things/grape-2.mp3",
    HAT_1_mp3: "res/sounds/things/hat-1.mp3",
    HAT_2_mp3: "res/sounds/things/hat-2.mp3",
    JAR_1_mp3: "res/sounds/things/jar-1.mp3",
    JAR_2_mp3: "res/sounds/things/jar-2.mp3",
    JOKER_1_mp3: "res/sounds/things/joker-1.mp3",
    JOKER_2_mp3: "res/sounds/things/joker-2.mp3",
    KITE_1_mp3: "res/sounds/things/kite-1.mp3",
    KITE_2_mp3: "res/sounds/things/kite-2.mp3",
    LAMP_1_mp3: "res/sounds/things/lamp-1.mp3",
    LAMP_2_mp3: "res/sounds/things/lamp-2.mp3",
    MAP_1_mp3: "res/sounds/things/map-1.mp3",
    MAP_2_mp3: "res/sounds/things/map-2.mp3",
    ORANGE_1_mp3: "res/sounds/things/orange-1.mp3",
    ORANGE_2_mp3: "res/sounds/things/orange-2.mp3",
    POTATO_1_mp3: "res/sounds/things/potato-1.mp3",
    POTATO_2_mp3: "res/sounds/things/potato-2.mp3",
    TOWEL_1_mp3: "res/sounds/things/towel-1.mp3",
    TOWEL_2_mp3: "res/sounds/things/towel-2.mp3",
    UMBRELLA_1_mp3: "res/sounds/things/umbrella-1.mp3",
    UMBRELLA_2_mp3: "res/sounds/things/umbrella-2.mp3",
    VEST_1_mp3: "res/sounds/things/vest-1.mp3",
    VEST_2_mp3: "res/sounds/things/vest-2.mp3",
    WATCH_1_mp3: "res/sounds/things/watch-1.mp3",
    WATCH_2_mp3: "res/sounds/things/watch-2.mp3",
    KEY_1_mp3:"res/sounds/things/key-1.mp3",
    KEY_2_mp3:"res/sounds/things/key-2.mp3",
    JOCKER_1_mp3:"res/sounds/things/jocker-1.mp3",
    JOCKER_2_mp3: "res/sounds/things/jocker-2.mp3",
    SOCK_1_mp3: "res/sounds/things/sock-1.mp3",
    SOCK_2_mp3: "res/sounds/things/sock-2.mp3",
    STRAWBERRY_1_mp3: "res/sounds/things/strawberry-1.mp3",
    STRAWBERRY_2_mp3: "res/sounds/things/strawberry-2.mp3",
    PEN_1_mp3: "res/sounds/things/pen-1.mp3",
    PEN_2_mp3: "res/sounds/things/pen-2.mp3",
    LEMON_1_mp3:"res/sounds/things/lemon-1.mp3",
    LEMON_2_mp3: "res/sounds/things/lemon-2.mp3",
    MEDICINE_1_mp3: "res/sounds/things/medicine-1.mp3",
    MEDICINE_2_mp3: "res/sounds/things/medicine-2.mp3",
    NAIL_1_mp3: "res/sounds/things/nail-1.mp3",
    NAIL_2_mp3: "res/sounds/things/nail-2.mp3",
    NEST_1_mp3: "res/sounds/things/nest-1.mp3",
    NEST_2_mp3: "res/sounds/things/nest-2.mp3",
    ONION_1_mp3: "res/sounds/things/onion-1.mp3",
    ONION_2_mp3: "res/sounds/things/onion-2.mp3",
    PEN_1_mp3: "res/sounds/things/pen-1.mp3",
    QUEEN_1_mp3: "res/sounds/things/queen-1.mp3",
    QUEEN_2_mp3: "res/sounds/things/queen-1.mp3",
    SALT_1_mp3: "res/sounds/things/salt-1.mp3",
    SALT_2_mp3: "res/sounds/things/salt-2.mp3",
    TEACHER_1_mp3: "res/sounds/things/teacher-1.mp3",
    TEACHER_2_mp3: "res/sounds/things/teacher-2.mp3",
    UNIFORM_1_mp3: "res/sounds/things/uniform-1.mp3",
    UNIFORM_2_mp3: "res/sounds/things/uniform-2.mp3",
    VEHICLE_1_mp3: "res/sounds/things/vehicle-1.mp3",
    VEHICLE_2_mp3: "res/sounds/things/vehicle-2.mp3",
    WATERMELON_1_mp3: "res/sounds/things/waterlemon-1.mp3",
    WATERMELON_2_mp3: "res/sounds/things/waterlemon-2.mp3",
    XMAS_1_mp3: "res/sounds/things/xmas-1.mp3",
    XMAS_2_mp3: "res/sounds/things/xmas-2.mp3",
    XYLOPHONE_1_mp3: "res/sounds/things/xylophone-1.mp3",
    XYLOPHONE_2_mp3: "res/sounds/things/xylophone-2.mp3",
    ABACUS_1_mp3: "res/sounds/things/abacus-1.mp3",
    ERASER_1_mp3: "res/sounds/things/eraser-1.mp3",
    FEATHER_1_mp3: "res/sounds/things/feather-1.mp3",
    FLAG_1_mp3: "res/sounds/things/flag-1.mp3",
    GIFT_1_mp3: "res/sounds/things/gift-1.mp3",
    INSECT_1_mp3: "res/sounds/things/insect-2.mp3",
    ABACUS_2_mp3: "res/sounds/things/abacus-2.mp3",
    ERASER_2_mp3: "res/sounds/things/eraser-2.mp3",
    FEATHER_2_mp3: "res/sounds/things/feather-2.mp3",
    FLAG_2_mp3: "res/sounds/things/flag-2.mp3",
    GIFT_2_mp3: "res/sounds/things/gift-2.mp3",
    INSECT_2_mp3: "res/sounds/things/insect-2.mp3",
    TOMATO_1_mp3: "res/sounds/things/tomato-1.mp3",
    TOMATO_2_mp3: "res/sounds/things/tomato-2.mp3",
    COMPUTER_1_mp3: "res/sounds/things/computer-1.mp3",
    COMPUTER_2_mp3: "res/sounds/things/computer-2.mp3",
    CRAYON_1_mp3: "res/sounds/things/crayon-1.mp3",
    CRAYON_2_mp3: "res/sounds/things/crayon-2.mp3",
    JUICE_1_mp3: "res/sounds/things/juice-1.mp3",
    JUICE_2_mp3: "res/sounds/things/juice-2.mp3",
    TOYTRAIN_1_mp3: "res/sounds/things/toytrain-1.mp3",
    TOYTRAIN_2_mp3: "res/sounds/things/toytrain-2.mp3",
 
    //countdown
    COUNTDOWN_mp3 : "res/sounds/Countdown.mp3",
    
    // BG sound 
    BACKGROUND_mp3: "sounds/background.mp3",
 
    Adidog_json: "Adidog/ConCho.json",
    Adidog_atlas: "AdiDog/ConCho.atlas",
    Adidog_png2: "AdiDog/ConCho.png",
 
    Plus_png: "plus.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}